<?php

namespace App\Commands;


use App\PathHelperInteface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class DevGenerateSwaggerYaml extends Command
{
    protected $pathHelper;

    public function __construct(PathHelperInteface $pathHelper)
    {
        parent::__construct();
        $this->pathHelper = $pathHelper;
    }

    protected function configure()
    {
        $this->setName('dev:generate:swagger_yaml');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}